const MASTERDENT={zr_strat:210,zr_pitt:170,digital:150,total:355,scheletrata:435,provvisorio:32,ribasatura:110,riparazione:33};
const EURODENTAL={guide:{1:180,2:210,3:240,4:270,5:300},planning:199};
const EXT={'Otturazione semplice':[12,22,16,0,0,0],'Otturazione MOD':[18,32,24,0,0,0],'Ricostruzione estetica anteriore':[20,38,28,0,0,0],'Endodonzia monoradicolato':[18,35,25,0,0,0],'Endodonzia biradicolare':[24,45,33,0,0,0],'Endodonzia pluriradicolato':[30,60,42,0,0,0],'Igiene professionale':[5,12,8,0,0,0],'Scaling e root planing quadrante':[8,18,12,0,0,0],'Chirurgia parodontale':[25,55,38,0,0,0],'Estrazione semplice':[8,18,12,0,0,0],'Estrazione chirurgica/complessa':[18,45,30,0,0,0],'Rigenerazione ossea guidata':[90,260,160,0,0,0],'Grande rialzo seno mascellare':[150,350,230,0,0,0],'Apparecchio fisso':[40,100,65,0,0,0],'Allineatori Express/Light':[15,35,22,350,900,600],'Allineatori Comprehensive':[20,45,30,900,1800,1300],'Contenzione / retainer':[8,20,12,60,180,100]};
function range(v,p=.12){return {min:+(v*(1-p)).toFixed(2),max:+(v*(1+p)).toFixed(2),suggested:+v.toFixed(2)}}
async function aiMaterials(p,used,variant){const key=process.env.ANTHROPIC_API_KEY;if(!key||!used)return null;const prompt=`Prestazione odontoiatrica: ${p}. Variante: ${variant||'standard'}. Materiali/prodotti dichiarati dallo studio: ${used}. Stima in EUR il costo CONSUMATO per singola prestazione, non il prezzo dell'intera confezione. Se un prodotto non è identificabile, amplia il range. Rispondi solo JSON: {"min":numero,"max":numero,"suggested":numero}`;try{const r=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"x-api-key":key,"anthropic-version":"2023-06-01","content-type":"application/json"},body:JSON.stringify({model:"claude-sonnet-4-6",max_tokens:150,messages:[{role:"user",content:prompt}]})});if(!r.ok)return null;const d=await r.json();const t=d.content?.[0]?.text||'';const q=JSON.parse((t.match(/\{[\s\S]*\}/)||[])[0]||t);return {min:+q.min,max:+q.max,suggested:+q.suggested}}catch{return null}}
exports.handler=async event=>{if(event.httpMethod!=='POST')return{statusCode:405,body:JSON.stringify({error:'Metodo non consentito'})};let x={};try{x=JSON.parse(event.body||'{}')}catch{return{statusCode:400,body:JSON.stringify({error:'Richiesta non valida'})}}const p=x.prestazione||'';let m={min:0,max:0,suggested:0},e={min:0,max:0,suggested:0},ms='Benchmark esterno',es='Non applicabile',note='Stima esterna iniziale: non è ancora un Benchmark EPA Dental validato.';
if(EXT[p]){const a=EXT[p];m={min:a[0],max:a[1],suggested:a[2]};e={min:a[3],max:a[4],suggested:a[5]};if(a[5]>0)es='Benchmark esterno'}
if(p==='Intarsio / Onlay'){m=x.variant==='chairside'?{min:35,max:75,suggested:50}:{min:15,max:35,suggested:24};e=x.variant==='chairside'?range(0,0):{min:130,max:240,suggested:180};es=x.variant==='chairside'?'Non applicabile':'Benchmark esterno';note=x.variant==='chairside'?'Chairside: materiali di produzione/cementazione; nessun laboratorio esterno.':'Workflow con laboratorio: consumabili chairside + stima esterna del costo odontotecnico.'}
if(p==='Corona su dente'||p==='Corona su impianto'){const c=MASTERDENT[x.variant]||MASTERDENT.zr_pitt;m=p==='Corona su impianto'?{min:18,max:45,suggested:30}:{min:12,max:30,suggested:20};e=range(c,.08);es='Listino dello studio';note='Costo laboratorio da listino dello studio; materiali ancora su stima esterna.'}
if(p==='Protesi totale'){m={min:25,max:60,suggested:40};e=range(MASTERDENT.total,.08);es='Listino dello studio'}if(p==='Protesi scheletrata'){m={min:20,max:50,suggested:35};e=range(MASTERDENT.scheletrata,.08);es='Listino dello studio'}if(p==='Provvisorio in resina'){m={min:8,max:20,suggested:12};e=range(MASTERDENT.provvisorio,.08);es='Listino dello studio'}if(p==='Ribasatura'){m={min:5,max:15,suggested:8};e=range(MASTERDENT.ribasatura,.08);es='Listino dello studio'}if(p==='Riparazione / aggiunta dente o gancio'){m={min:3,max:10,suggested:6};e=range(MASTERDENT.riparazione,.08);es='Listino dello studio'}
if(p==='Chirurgia implantare guidata'){const n=x.variant||'1';m={min:35,max:90,suggested:55};const v=EURODENTAL.guide[n]+EURODENTAL.planning;e=range(v,.03);es='Listino dello studio';note='Dima + programmazione implantare da listino dello studio. Fixture e altri materiali implantari non inclusi.'}
if(p==='Impianto singolo'){const f=Number(x.fixture)||0;m=f?range(f+45,.1):{min:120,max:260,suggested:180};e={min:0,max:0,suggested:0};ms=f?'Dato inserito dallo studio + benchmark esterno':'Benchmark esterno';note=f?'Fixture indicata dallo studio + stima esterna dei consumabili/componenti chirurgici.':'Fixture non indicata: stima esterna iniziale da validare.'}
if(p==='All-on-implant provvisorio'){m={min:180,max:420,suggested:280};e={min:300,max:900,suggested:550};es='Benchmark esterno'}if(p==='All-on-implant definitivo'){m={min:200,max:500,suggested:320};e={min:900,max:2200,suggested:1500};es='Benchmark esterno'}
if(x.materials_used){const ai=await aiMaterials(p,x.materials_used,x.variant);if(ai){m=ai;ms='Benchmark esterno · materiali indicati dallo studio';note='Stima del consumo per prestazione basata sui materiali indicati. Da validare con prezzi/listini reali quando disponibili.'}}
if(x.real_external!==''&&x.real_external!=null){e=range(Number(x.real_external),0);es='Dato inserito dallo studio'}
return{statusCode:200,headers:{'content-type':'application/json'},body:JSON.stringify({materials:m,external:e,materials_source:ms,external_source:es,note})}}